authors:
  NekoMirra:
    name: NekoMirra
    description: AcWiki 发起人
    avatar: https://github.com/NekoMirra.png
    url: https://mirradev.eu.org/
  ztm0929:
    name: 天明 (@ztm0929)
    description: AcWiki 成员
    avatar: https://github.com/ztm0929.png
    url: https://github.com/ztm0929
